spring:
  application:
    name: dividends

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      # 프로젝트 실행때마다 db를 초기화
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dividends;DB_CLOSE_DELAY=-1
    username: sa
    password: